CREATE TABLE res_operation (
  op_type VARCHAR2(10) NOT NULL,
  op_date DATE NOT NULL,
  IDRES NUMBER(11),
  CIN NUMBER(30),
  IDTERR NUMBER(30),
  NBPERSONNE NUMBER(2),
  REMARQUE VARCHAR2(30),
  STATUS varchar(30),
  DTTAKWIRA varchar(30),
  RECHERCHEBLASSA number(2)
);

CREATE OR REPLACE TRIGGER op_trigger
AFTER INSERT OR UPDATE OR DELETE ON reservation
FOR EACH ROW
DECLARE
  v_op_type VARCHAR2(10);
BEGIN
  IF INSERTING THEN
    v_op_type := 'INSERT';
  ELSIF UPDATING THEN
    v_op_type := 'UPDATE';
  ELSIF DELETING THEN
    v_op_type := 'DELETE';
  END IF;
  INSERT INTO res_operation (op_type, op_date, IDRES, CIN, IDTERR, NBPERSONNE, REMARQUE, STATUS , DTTAKWIRA ,RECHERCHEBLASSA)
  VALUES (v_op_type, SYSDATE, :OLD.IDRES, :OLD.CIN, :OLD.IDTERR, :OLD.NBPERSONNE, :OLD.REMARQUE, :OLD.STATUS , :OLD.DTTAKWIRA , :OLD.RECHERCHEBLASSA);
END;







